services:
  minicommerce.api:
    image: minicommerce.api
    build:
      context: .
      dockerfile: MiniCommerce.API/Dockerfile
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    

